version: '3'
services:
  web:
    build: .
    container_name: flask-app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: python app.py
